### ISSUE TITLE
Object Validator : kill a dead object and push a new one to the pool

### ISSUE THREAD

**Issue by manuprendlair** [mediatechsolutions/blocking-object-pool#1]
Hello,

This is not really an issue, just a question:

With the object Validator it is possible to detect if an object is dead (lock or what ever else)
What to do after? A common need is to "kill" object and instantiate a new one in the pool.
Is it possible ?
(I would like to rugged my pool as much as possible)

Regards.
Emmanuel from France, C# advanced beginner ;-)

**Comment by manuprendlair** [comment]
hum I think my question is kinde of stupid..
on readme its write : Configurable validation when objects are acquired from or returned to the pool. Objects that fail to validate are invalidated and re-created.
Could you add sample code to work with this feature?

**Comment by rubms** [comment]
After detecting an object is dead via the validation, the library will automatically remove it from the pool and create a new one, which is what I understand you need. This way, you can just define your own validations for the pooled objects and the library will take care of validating them and removing from the pool/creating a new one.

The factory you provide for creating pooled objects can also define how to destroy them in the Destroy method. After an object has been detected invalid, your factory Destroy method will be invoked passing the object as a parameter. There you can "kill" your object according to your application logic.
